spring:
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        defer-datasource-initialization: true
    datasource:
        url: jdbc:mysql://localhost:3306/DDProject
        username: ${your_username}
        password: ${your_password}
        driver-class-name: com.mysql.cj.jdbc.Driver
    h2:
        console:
            enabled: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB

jwt:
    secret_key: ${jwt.secret_key}

